version: '2'

services:
#  postgres:
#    image: postgres:9.6
  mysql:
#    container_name: mymysql
#    ports:
#      - "3306:3306"
#    command: [
#            '--character-set-server=utf8mb4',
#            '--collation-server=utf8mb4_unicode_ci'
#    ]
#    environment:
#      MYSQL_ROOT_PASSWORD: "123456"
    restart: "no"
    build: ./mysql/
    volumes:
      - /home/rock/Desktop/db/mysql/data

    expose:
      - 3306

  redis:
    restart: always
    image: redis:latest
    volumes:
      - /home/rock/Desktop/db/redis


  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
#    volumes_from:
#      - web
    volumes:
      - ./static/:/static/
    links:
      - web


  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    image: web
    build: ./
    command: >
      bash -c "python wait_for_mysql.py &&
               ./manage.py migrate &&
               ./manage.py collectstatic --noinput &&
              newrelic-admin run-program gunicorn --bind 0.0.0.0:8000 --access-logfile - piedpiper.wsgi:application"
    volumes:
      - ./:/code
#    ports:
#      - "8000:8000"
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis

 #   entrypoint: /code/entrypoint.sh -d mysql:3306 -c 'echo "start web service here"';
#



